### ISSUE TITLE
[Feature]allow us to customize the sorting of files

### ISSUE THREAD

**Issue by Quorafind** [ozntel/file-tree-alternative#1]
Is it doable that the plugin allows us to customize the sorting of files ? I heard some people request this.

**Comment by ozntel** [comment]
Hi, I just released a version, which includes a feature to `pin` files to the top. It is not exactly what you are searching for but it might be helpful for your request. 
As for your request, I will see what I can do in the feature. Since it requires the implementation of `drag and drop`, it will require some work.
Cheers!
