### ISSUE TITLE
"Expand folders" action doesn't work when "Folder count" option is disabled in plugin settings

### ISSUE THREAD

**Issue by georgebyte** [ozntel/file-tree-alternative#124]
Hello,

after digging through the code I found the following cause for the issue described in the title:

`setFolderFileCountMap` is only ever called when `plugin.settings.folderCount` is `true`. Otherwise `folderFileCountMap` state is always an empty array, which causes the `forEach` in `https://github.com/ozntel/file-tree-alternative/blob/main/src/components/FolderView/MainFolder.tsx#L83` to never add any folders to `newOpenFolders` and in the end calling `setOpenFolders([])` which erroneously collapses all the folders.

Simply removing the `if(plugin.settings.folderCount)` condition before calling `setFolderFileCountMap` would solve the issue, but I'm not sure how impactful this would be on performance and/or why was the condition needed in the first place.

**Comment by ozntel** [comment]
Thanks for flagging this. It was actually not logical to use `folderFileCountMap` since I created this only to have constant reference for number of files under each folder. And it wouldn't be efficient if I kept populating it even if you don't have counts enabled.

I am now using `folderTree` that I create to show to folders in the view. It is definitely a better approach.

I released the version with the fix. Let me know if you still have the issue. 

Thanks!
