### ISSUE TITLE
Dragging into excalidraw is not fully working. 

### ISSUE THREAD

**Issue by ksdavidc** [ozntel/file-tree-alternative#197]
Dragging into excalidraw is not fully working. See https://github.com/excalidraw/excalidraw/issues/7565#issue-2082653734 for more info. Certain formats do not paste or paste strangely.

**Comment by ozntel** [comment]
There was a bug that was fixed a few months ago in the plugin. Now the links that you bring from the plugin to Excalidraw or any other place should be ok. The path depends on what you select in Obsidian settings. If you only want the file name, you should select "Shortest Path when Possible" under Files and Links:

<img width="791" alt="image" src="https://github.com/excalidraw/excalidraw/assets/55187568/ee8c120e-efcc-48eb-b29a-0ab59cdd74b8">

Btw - you opened an issue for Excalidraw itself but not the Obsidian Excalidraw Plugin as far as I can see. You should close since it is not relevant to them
