### ISSUE TITLE
CSS snippets don't work with File Tree Alternative

### ISSUE THREAD

**Issue by btbristow** [ozntel/file-tree-alternative#208]
Hi! I used the Style Settings plugin to change file and folder name font sizes, since these are too small (especially the file names). But, that didn't work on iOS. I tried the following as a CSS snippet (loaded under Settings > Appearance):

```
/* Desktop File Tree Alternative font size */
.file-tree-alternative-plugin .oz-fta-folder {
  font-size: 1rem;
}

.file-tree-alternative-plugin .oz-fta-file {
  font-size: 1rem;
}

/* Mobile File Tree Alternative font size */
@media (max-width: 600px) {
  .file-tree-alternative-plugin .oz-fta-folder {
    font-size: 1.2rem;
  }

  .file-tree-alternative-plugin .oz-fta-file {
    font-size: 1.2rem;
  }
}
```
That doesn't work either. Are CSS snippets unsupported, or is that just wrong? Thanks!

**Comment by ozntel** [comment]
Please try to use the Style Settings plugin. I created an interface so that you can adjust the font-size without writing your own CSS Snippet. 


<img width="708" alt="image" src="https://github.com/ozntel/file-tree-alternative/assets/55187568/f3a0e3b5-dfd7-43c7-b92a-c882cd9d918d">

Let me know in case you encounter any issues. Thanks
