### ISSUE TITLE
Files missing in other plugins

### ISSUE THREAD

**Issue by chetachiezikeuzor** [ozntel/file-tree-alternative#3]
Sorry for the double issue but I also noticed that the files can no longer be seen in other plugins:
- Starred Files (Core plugin)
- Recent Files (Community plugin)

<img width="287" alt="Screen Shot 2021-06-11 at 11 28 41 AM" src="https://user-images.githubusercontent.com/79069364/121720849-2db43280-caa9-11eb-80b9-05d11eb68d19.png">

<img width="287" alt="Screen Shot 2021-06-11 at 11 27 48 AM" src="https://user-images.githubusercontent.com/79069364/121720880-36a50400-caa9-11eb-8293-e81bdfe4676a.png">

**Comment by ozntel** [comment]
Hi, it was because of the snippet below:

```css
.nav-file:not(.oz-nav-file) { 
    display: none !important;
}
```

Since I changed the way of working totally due to the fact that Obsidian gives very limited possibility to manipulate its own file explorer, this snippet was also removed. I also have full control right now on what I can include what now. 

More to come! :)

**Comment by chetachiezikeuzor** [comment]
Thank you!! ☺️
