### ISSUE TITLE
Slight lag

### ISSUE THREAD

**Issue by rasmusrhl** [ozntel/file-tree-alternative#39]
I think this plugin causes a slight periodic lag in typing. This disappears when I disable the plugin.

**Comment by ozntel** [comment]
I don't think it is related to the File Tree Alternative plugin. I have tried in many machines and also with 6x slower CPU in Obsidian and there was no lag issue.

**Comment by thomasvs** [comment]
I experience the same issue; since I couldn't reopen this issue created a new one, #47

**Comment by javiavid** [comment]
I have the same problem. I have discovered that it happens when the filetree panel is displayed, if I click on another panel the problem disappears.

obsidian 1.1.9
windows 11

To make it more clear:

slow typing
![image](https://user-images.githubusercontent.com/7627504/210130128-75d6cefb-6aae-43f7-adae-e283b1f42b44.png)


fast typing
![image](https://user-images.githubusercontent.com/7627504/210130151-f242149a-e889-470e-8183-927a7563efd1.png)
