### ISSUE TITLE
Feature request: Move files by dragging files from file list to folder list

### ISSUE THREAD

**Issue by that0n3guy** [ozntel/file-tree-alternative#42]
It would be awesome if you could simply move around files by dragging: 
![image](https://user-images.githubusercontent.com/113870/146582620-846369e7-794f-4e51-9c61-9664188fcf01.png)

**Comment by ih8snow** [comment]
I support this idea, would be really helpful!

**Comment by ozntel** [comment]
It is available in the new release.
I still need to work on it since dragging needs to be firstly initiated like in the following video. 

https://user-images.githubusercontent.com/55187568/160246226-83f9d3d8-5b1c-4342-8c82-390aef87dab3.mov

Dragging needs to get out of the pane and then you can drop in a folder.
Will try to find a solution for this.

**Comment by ih8snow** [comment]
Great! many thanks!

**Comment by hqweay** [comment]
it's a bit tricky really, but great to hear it works at least.
