### ISSUE TITLE
[Enhancement] Add compatibility with Folder Note

### ISSUE THREAD

**Issue by Mara-Li** [ozntel/file-tree-alternative#9]
For the moment, when clicked on a folder, it always "just" open it. But, it will be good to have the note opened if we use folder note (+ Open the folder).

The folder note always have the same name of the folder, if it can help.

**Comment by ozntel** [comment]
To be honest, I didn't understand what you mean exactly

**Comment by Mara-Li** [comment]
Folder Note is a [plugin from xpgo](https://forum.obsidian.md/t/folder-note-plugin-add-description-note-to-folder/12038), and there is a [rewrite from AidenLx](https://github.com/alx-plugins/alx-folder-note).

The purpose of the plugin is to "link" note to a folder. When you click on the folder, a note appear. Moreoever, the synced file is hided in the explorer.

It will be good to have a similar thing with filetree, to open a note with same name of the folder directly after open a folder, and hide the note in the file.

**Comment by ozntel** [comment]
I am afraid it will be hard. 

I would need to have access to the main function of the plugin you mentioned from the `window` objects so that I can add an event handler `click + ctrl` to trigger. 

@AidenLx would you be able to give access to the `main` function triggered by the `click + ctrl` event so that I can add to the `file-tree-alternative` plugin? 

zsviczian did something like that for the `oz-image-in-editor` plugin when we implemented `excalidraw` drawings into editor. You can see our discussion below:

https://github.com/ozntel/oz-image-in-editor-obsidian/issues/15#issuecomment-843809184

**Comment by AidenLx** [comment]
Actually, I've added an event listener to titleInnerEl (`div.nav-folder-title-content`) in [here](https://github.com/alx-plugins/alx-folder-note/blob/11465298acc3ea39dfeceb8c1a816e8eb41a0bfd/src/modules/fe-handler.ts#L91), and the event handler is [here](https://github.com/alx-plugins/alx-folder-note/blob/11465298acc3ea39dfeceb8c1a816e8eb41a0bfd/src/modules/click-handler.ts#L5). What it does is essentially loop through TFolder's children/parent to see if any file matches the rule of folder note. 
I don't have time to read your code yet so I may not be about to add support to this myself, but feel free to contribute anyway :)

**Comment by ozntel** [comment]
If Aiden manages to make available the function, which I can trigger with a custom event, I can implement but I need to have this available in `window` object.

@aidenlx I see that the trigger requires your plugin as an argument, which I can not provide from my side. If you create any custom function, which only requires objects from Obsidian's API (like `TFile`, `TFolder` for which `folder note` needs to be opened or `app` etc) and push this function to `window` object, I can check if your plugin is loaded and then trigger this custom function from `window` to open the `folder note` once the certain even happens (like ctrl + click or context menu in `file tree`). You don't need to read anything from `file tree alternative` but just give me an access to your plugin with a small function :)

@Mara-Li I will close this issue for the moment but I will work on it once such function is available for me.

**Comment by aidenlx** [comment]
oh good news here, I've separate the api from the folder note plugin as [folder-note-core](https://github.com/aidenlx/folder-note-core), you should be able to use `npm i -D @aidenlx/folder-note-core` to use api, you can check README for details of how to use API, and here are all functions exposed in the API: https://github.com/aidenlx/folder-note-core/blob/master/src/typings/api.ts

btw if you are using built-in `file-menu` to trigger context menu, you won't need to do anything to have quick actions to manipulate folder notes.

**Comment by aidenlx** [comment]
@Mara-Li maybe you should list those features you need the most from the patched file explorer by folder note plugin. 

I've opened a [new feature request](https://github.com/aidenlx/folder-note-core/issues/3) in folder-note-core repo for a folder menu option to open folder notes, meanwhile, if you need to implement "click folder title to open folder note, elsewhere to collapse folder", here are the code that might be helpful: https://github.com/aidenlx/alx-folder-note/blob/517c55e1836ec40ca924125ec0f7fa69f6a4263e/src/modules/click-handler.ts#L29-L52

**Comment by ozntel** [comment]
@Mara-Li - 

I just implemented the same functionality what Folder Note Plugin provides. 

If there is a note for a folder, the plugin will have an arrow on the right side of the folder so that you can easily identify which folders have its notes. 

It is capable of working standalone (no need to have folder note core installed) but checks if Folder note Core is enabled anyway to not duplicate "Create/Delete Folder Note" buttons in the context menu. 

Single Click will open the file list for the folder, "Click + Shift" will open the folder note in the active pane.

You need to enable first from the plugin settings to use it. 

Let me know if there is any issue.
